// <auto-generated />
namespace BTL_LTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1K : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1K));
        
        string IMigrationMetadata.Id
        {
            get { return "202112051037379_1K"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
